# Welcome to Jekyll!
#

# Site settings
title: Ajay Rahul
description: |
  Hey! This is my Blog! Cheers!




owner: Ajay Rahul # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ajayrahul97@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajayrahul97.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Ajayrahul_P
  github: https://github.com/ajayrahul97
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/ajay.rahul.39
  google-plus-square: https://plus.google.com/u/0/+ajayrahul97
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
